// Fluffle.UI/src/app/pages/about/about.component.ts
import { Component } from '@angular/core';
import { ContentCenterService } from 'src/app/content-center.service';
import { SvgService } from 'src/app/svg.service';
import { TitleService } from 'src/app/title.service';

@Component({
  selector: 'app-about',
  templateUrl: './about.component.html',
  styleUrls: ['./about.component.scss']
})
export class AboutComponent {
  constructor(titleService: TitleService, contentCenterService: ContentCenterService, public svg: SvgService) {
    titleService.title = "About";
    contentCenterService.center();
  }
}

<div class="about-container">
    <h1 class="text-center my-5">
        <img class="fluffle-banner d-inline-block align-top me-1" [src]="svg.get('banner')" height="100"
            alt="Fluffle">
    </h1>

    <p>
        Fluffle is an initiative taken by me, <a routerLink="/contact">Noppes</a>, with the goal to eventually create a single
        unified platform for fellow furries with which they can reverse search artwork from a variety of sources. However, at
        the moment Fluffle only has support for e621 due to them providing an easy way for developers to integrate with their
        service.
    </p>
    <p>
        In its early stages Fluffle will remain closed source, but I might decide to make it public domain under the GPLv3 (The
        GNU General Public License v3.0) license in the future.
    </p>
    <a name="privacy">
        <h2>Privacy</h2>
    </a>
    <p>
        Fluffle has been created with privacy in mind from the start. Due to Fluffle its scope being limited – after
        all, you can only reverse search images – we can ensure Fluffle respects your privacy.
    </p>
    <p>
        When you reverse search an image on Fluffle, the image gets stored temporarily on our servers for processing.
        Processing only contains fingerprinting the image. That is creating an identifier which can be used to compare
        indexed images. Once the fingerprint is created, the submitted image gets permanently deleted immediately. The
        aforementioned fingerprint also doesn’t get stored and neither do the settings used for reverse searching.
    </p>
    <p>
        Said settings, from here on called preferences, are stored in your browser its so-called local storage. You can
        think of this as a small place in which websites can store a small amount of data. These preferences are only
        sent to Fluffle whenever you submit an image for reverse searching, and as said before, are immediately
        discarded when they are not required anymore for fulfilling your request.
    </p>
    <a name="cookies">
        <h2>Cookies</h2>
    </a>
    <p>
        The only cookies Fluffle makes use of, are those required for the services provided by Cloudflare. At this
        moment, Cloudflare only requires the use of the <code>__cfduid</code> cookie. Despite its misleading name, it
        is only used
        by Cloudflare for detecting malicious visitors. So, you are not being tracked in any way. In fact, from the May
        10 they are going to <a href="https://blog.cloudflare.com/deprecating-cfduid-cookie/" target="_blank">stop using it altogether</a>.
    </p>
    <p>
        If you would like to learn more about Cloudflare its cookie usage, we kindly refer you to <a
            href="https://support.cloudflare.com/hc/en-us/articles/200170156-Understanding-the-Cloudflare-Cookies"
            target="_blank">Cloudflare its website</a>
        where they are thoroughly explained.
    </p>
</div>

// Fluffle.UI2/src/pages/about.tsx
import { Link } from 'gatsby'
import * as React from 'react'
import Layout from '../components/layout'
import Banner from '../components/banner'

const AboutPage = () => {
    return (
        <Layout center={true} title="About" maxWidth="2xl">
            <div className="my-12 text-center">
                <Banner></Banner>
            </div>
            <div className="prose max-w-none">
                <p>
                    Fluffle is an initiative taken by me, <Link to="/contact/" >Noppes</Link>, with the goal to eventually create a single
                    unified platform for fellow furries with which they can reverse search artwork from a variety of sources. In its early
                    stages Fluffle will remain closed source, but I might decide to make it public domain under the GPLv3 (The GNU General
                    Public License v3.0) license in the future.
                </p>
                <a id="privacy">
                    <h2>Privacy</h2>
                </a>
                <p>
                    When you reverse search an image on Fluffle, the image gets stored temporarily on our servers for processing.
                    Processing only contains fingerprinting the image. That is creating an identifier which can be used to compare
                    indexed images. Once the fingerprint is created, the submitted image gets permanently deleted immediately. The
                    aforementioned fingerprint also doesn’t get stored and neither do the settings used for reverse searching.
                </p>
                <p>
                    Said settings are stored in your browser its so-called local storage. You can
                    think of this as a place in which websites can store a small amount of data. These preferences are only
                    sent to Fluffle whenever you submit an image for reverse searching, and as said before, are immediately
                    discarded when they are not required anymore for fulfilling your request.
                </p>
                <p>
                    However, we do log a few things regarding your request. These are strictly used for assessing server performance and request throttling/blocking. The following information is being logged:
                </p>
                <ul>
                    <li>The origin of the request, needed to identify malicious clients and block them.</li>
                    <li>User Agent, for a normal user, this would be the web browser and the version of said web browser. Also used to identify malicious clients. Mainly used to identify which applications are making use of Fluffle its API.</li>
                    <li>If your request caused the server to error out for whatever reason, the corresponding stack trace of the occurred exception gets logged. We can use this information to determine what caused your request to fail if you decide to contact us and provide us with a trace ID, the used image and the settings used.</li>
                    <li>The format in which the image is encoded and its width and height. These three image attributes correlate highly with the time needed to process your request. It is therefore used to assess server performance. Its also used to identify API clients that don’t follow the guidelines put up by Fluffle.</li>
                    <li>The moment at which the server started processing your request. This can be used to assess server performance in scenarios where there are a lot of request being processed in parallel.</li>
                    <li>The how manyth request it is since the start of the server. Used to assess server performance.</li>
                    <li>A bunch of timings. You can compare this to having a stopwatch and tracking laps, but in application code. How long did it take to create the fingerprint? How long did it take to check if the submitted file was an image? How long did it take to compare the fingerprint? Etc. Used to assess server performance.</li>
                    <li>The number of images compared against. Used to assess server performance.</li>
                </ul>
                <a id="privacy">
                    <h2>Tracking & cookies</h2>
                </a>
                <p>
                    Fluffle uses <a href="https://www.cloudflare.com/web-analytics/" target="_blank" rel="noreferrer">Cloudflare its web analytics platform</a>.
                    They do not collect personal information and also do not track your browsing behavior. They do not make use of cookies and neither do we, meaning Fluffle is cookie free.
                </p>
            </div>
        </Layout>
    )
}

export default AboutPage
