// Fluffle.UI/src/pages/contact.tsx
import * as React from 'react'
import Layout from '../components/layout'
import { StaticImage } from 'gatsby-plugin-image'
import Icon from '../components/icon'

const artistName = 'Oggy123'
const artUrl = 'https://twitter.com/OggyOsbourne/status/1294700124187262976'

const socials = [
    { name: 'Telegram', url: 'https://t.me/NoppesTheFolf', icon: 'fa-telegram-plane' },
    { name: 'Twitter', url: 'https://twitter.com/NoppesTheFolf', icon: 'fa-twitter' },
    { name: 'GitHub', url: 'https://github.com/NoppesTheFolf', icon: 'fa-github-alt' }
];

const SocialBadge = ({ social }) => {
    return (
        <a className="transition-colors m-2 text-4xl fill-light-100 hover:fill-dark-400 hover:bg-light-100 p-3 rounded-full border-2" href={social.url} target="_blank" rel="noreferrer">
            <Icon inheritSize={true} name={social.icon} />
        </a>
    )
}

const ContactPage = () => {
    return (
        <Layout center={true} title="Contact">
            <div className="flex flex-col items-center space-y-6 text-center">
                <div>
                    <a href={artUrl} target="_blank" rel="noreferrer">
                        <StaticImage alt={`NoppesTheFolf icon by ${artistName}`} className="w-64 rounded-full" src="../images/noppes.jpg" />
                    </a>
                    <div className="italic">
                        <span className="text-muted">Art by </span>
                        <a href={artUrl} target="_blank" rel="noreferrer">{artistName}</a>
                    </div>
                </div>
                <div>
                    <div className="w-72 sm:w-full">
                        Found a bug? Got a feature request? Contact a folf.
                    </div>
                </div>
                <div className="flex flex-wrap justify-center items-center">
                    {socials.map(s => (
                        <SocialBadge key={s.name} social={s}></SocialBadge>
                    ))}
                </div>
            </div>
        </Layout>
    )
}

export default ContactPage

// Fluffle.UI/src/app/pages/contact/contact.component.ts
import { Component, OnInit } from '@angular/core';
import { ContentCenterService } from 'src/app/content-center.service';
import { TitleService } from 'src/app/title.service';

@Component({
  selector: 'app-contact',
  templateUrl: './contact.component.html',
  styleUrls: ['./contact.component.scss']
})
export class ContactComponent implements OnInit {
  constructor(titleService: TitleService, contentCenterService: ContentCenterService) {
    titleService.title = "Contact";
    contentCenterService.center();
  }

  ngOnInit(): void {
  }
}

<div class="d-flex flex-column h-100 text-center">
    <div>
        <div class="d-flex justify-content-center">
            <a href="https://twitter.com/OggyOsbourne/status/1294700124187262976" target="_blank">
                <img class="rounded-circle d-block" src="/assets/img/noppes.jpg" width="256" height="256" alt="NoppesTheFolf icon by Oggy123" />
            </a>
        </div>
        <i class="text-muted">Art by <a href="https://twitter.com/OggyOsbourne/status/1294700124187262976" target="_blank">Oggy123</a></i>
    </div>
    <div class="mt-4">
        A sporadically motivated, coffee addicted, folf from the Netherlands that happens to exists in the same universe as you do.
    </div>
    <div class="mt-4 d-flex justify-content-center">
        <a class="btn-social" href="https://twitter.com/NoppesTheFolf" target="_blank">
            <span class="fab fa-twitter"></span>
        </a>
        <a class="btn-social" href="https://t.me/NoppesTheFolf" target="_blank">
            <span class="fab fa-telegram-plane"></span>
        </a>
    </div>
</div>
