// Fluffle.UI2/src/components/navbar.tsx
import { Link } from 'gatsby'
import * as React from 'react'
import Svg from '../services/svg'
import Icon from './icon'
import './navbar.scss'

const NavbarItem = ({ href, icon, children }) => {
    return (
        <Link to={href} activeClassName="navbar-item-active" className="navbar-item select-none gap-1.5">
            <span className="hidden md:inline"><Icon name={icon} /></span>
            <span>{children}</span>
        </Link>
    )
}

const Navbar = () => {
    return (
        <header className="hidden sm:flex justify-between items-center py-2 w-full">
            <Link to="/" className="flex items-center text-light-100 hover:text-light-200 cursor-pointer select-none">
                <img className="h-8 mr-2" src={Svg.get("tail")} alt="Fluffle brand logo"></img>
                <span className="block text-xl">Fluffle</span>
            </Link>
            <nav>
                <div className="flex flex-wrap gap-x-2 md:gap-x-3 lg:gap-x-8">
                    <NavbarItem href="/" icon="youtube-searched-for">Reverse search</NavbarItem>
                    <NavbarItem href="/about/" icon="info">About</NavbarItem>
                    {/* <NavbarItem href="/status/" icon="dns">Status</NavbarItem> */}
                    <NavbarItem href="/api/" icon="code">API</NavbarItem>
                    <NavbarItem href="/contact/" icon="mail">Contact</NavbarItem>
                </div>
            </nav>
        </header>
    )
}

export default Navbar

// Fluffle.UI/src/app/navbar/navbar.component.ts
import { Component } from '@angular/core';
import { SvgService } from '../svg.service';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.scss']
})
export class NavbarComponent {

  constructor(public svg: SvgService) { }

}

<div class="container d-none d-md-block mb-3">
    <nav class="navbar navbar-expand-md navbar-dark">
        <div class="container-fluid">
            <a class="navbar-brand" routerLink="/" appReload>
                <img [src]="svg.get('tail')" height="30" class="d-inline-block align-top me-1" alt="">
                Fluffle
            </a>
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav flex-grow-1 justify-content-end">
                    <li class="nav-item">
                        <a class="nav-link" routerLink="/" appReload routerLinkActive="nav-link-active"
                            [routerLinkActiveOptions]="{exact: true}">
                            <i class="fas fa-undo me-2 d-none d-md-inline-block"></i>Reverse search
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" routerLink="/about" routerLinkActive="nav-link-active">
                            <i class="fas fa-info me-2 d-none d-md-inline-block"></i>About
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" routerLink="/contact" routerLinkActive="nav-link-active">
                            <i class="fas fa-envelope me-2 d-none d-md-inline-block"></i>Contact
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</div>
