// Fluffle.UI2/src/components/navbar-mobile.tsx
import { Link } from 'gatsby'
import * as React from 'react'
import classNames from 'classnames'
import './navbar-mobile.scss'
import Icon from './icon'

const NavbarItemMobile = ({ href, icon, children }) => {
    return (
        <Link to={href} className="navbar-item-mobile" activeClassName="navbar-item-active-mobile">
            <span className="flex flex-col justify-center items-center">
                <Icon name={icon} />
                <div className="text-sm">{children}</div>
            </span>
        </Link>
    )
}

const NavbarMobile = ({ isDummy }) => {
    return (
        <nav className={classNames("flex justify-center sm:hidden pb-2 pt-4 bg-dark-300 bottom-0 left-0 w-full border-t border-dark-500 gap-x-6", { fixed: !isDummy })}>
            <NavbarItemMobile href="/" icon="youtube-searched-for">Search</NavbarItemMobile>
            <NavbarItemMobile href="/about" icon="info">About</NavbarItemMobile>
            {/* <NavbarItemMobile href="/status" icon="dns">Status</NavbarItemMobile> */}
            <NavbarItemMobile href="/api" icon="code">API</NavbarItemMobile>
            <NavbarItemMobile href="/contact" icon="mail">Contact</NavbarItemMobile>
        </nav>
    )
}

export default NavbarMobile

// Fluffle.UI/src/app/navbar-mobile/navbar-mobile.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-navbar-mobile',
  templateUrl: './navbar-mobile.component.html',
  styleUrls: ['./navbar-mobile.component.scss']
})
export class NavbarMobileComponent {

  constructor() { }

}

<div id="f-navbar" class="f-navbar d-md-none">
    <div class="d-flex justify-content-center bg-dark pb-2 pt-3">
        <a class="px-4 f-navbar-item" routerLink="/" appReload routerLinkActive="f-navbar-link-active"
            [routerLinkActiveOptions]="{exact: true}">
            <i class="fas fa-undo d-block text-center f-navbar-item-icon"></i>
            <span class="f-navbar-item-text">Search</span>
        </a>
        <a class="px-4 f-navbar-item" routerLink="/about" routerLinkActive="f-navbar-link-active">
            <i class="fas fa-info d-block text-center f-navbar-item-icon"></i>
            <span class="f-navbar-item-text">About</span>
        </a>
        <a class="px-4 f-navbar-item" routerLink="/contact" routerLinkActive="f-navbar-link-active">
            <i class="fas fa-envelope d-block text-center f-navbar-item-icon"></i>
            <span class="f-navbar-item-text">Contact</span>
        </a>
    </div>
</div>
