// Fluffle.UI/src/app/gallery-thumbnail/gallery-thumbnail.component.ts
import { AfterViewInit, Component, ElementRef, Input, ViewChild } from '@angular/core';
import { SearchResponseThumbnail } from '../api.service';

@Component({
  selector: 'app-gallery-thumbnail',
  templateUrl: './gallery-thumbnail.component.html',
  styleUrls: ['./gallery-thumbnail.component.scss']
})
export class GalleryThumbnailComponent implements AfterViewInit {
  @Input("thumbnail") thumbnail: SearchResponseThumbnail;
  @Input("hasBlur") hasBlur: boolean;

  @ViewChild("imageElement") image: ElementRef<HTMLImageElement>;

  hasBeenLoaded: boolean;
  error: string;

  get hasError(): boolean {
    return this.error != null;
  }

  constructor() { }

  ngAfterViewInit(): void {
    let dlImage = new Image();

    dlImage.onload = () => {
      this.image.nativeElement.src = dlImage.src;
      this.hasBeenLoaded = true;
    };

    dlImage.onerror = () => {
      this.error = "Fluffle offline";
    };

    dlImage.src = this.thumbnail.location;
  }
}

<div class="position-relative w-100 h-100 overflow-hidden bg-darkest">
    <img class="gallery-image" [ngClass]="{
            blur: hasBlur
        }" [ngStyle]="{
            objectPosition: thumbnail.centerX + '% ' + thumbnail.centerY + '%',
            opacity: hasBeenLoaded ? '1' : '0'
        }" #imageElement>
    <div [ngClass]="{'d-none': !hasError}"
        class="error-container d-flex justify-content-center align-items-center text-center p-3">
        {{ error }}
    </div>
    <div class="skeleton" [ngClass]="{'d-none': hasBeenLoaded || hasError}"></div>
</div>

// Fluffle.UI/src/components/gallery-thumbnail.tsx
import * as React from 'react'
import { galleryThumbnail, blur, skeleton } from './gallery-thumbnail.module.scss'
import { SearchResultThumbnail } from '../services/api'
import classNames from 'classnames';

interface GalleryThumbnailProps {
    thumbnail: SearchResultThumbnail,
    hasBlur: boolean
}

const GalleryThumbnail = ({ thumbnail, hasBlur }: GalleryThumbnailProps) => {
    const [hasBeenLoaded, setHasBeenLoaded] = React.useState(false);
    const [error, setError] = React.useState(null);

    function load(element: HTMLImageElement) {
        if (element == null) return;

        const image = new Image();
        image.onload = () => {
            element.src = image.src;
            setHasBeenLoaded(true);
        };

        image.onerror = () => {
            setError('Fluffle offline');
        };

        image.src = thumbnail.location;
    }

    return (
        <div className="relative w-full h-full bg-dark-400 text-light-100">
            <img className={hasBlur ? classNames(galleryThumbnail, blur) : galleryThumbnail} style={{
                objectPosition: thumbnail.centerX + "% " + thumbnail.centerY + "%",
                opacity: hasBeenLoaded ? "1" : "0"
            }} ref={element => load(element)} />
            <div className={classNames("absolute w-full h-full top-0 left-0 text-2xl flex text-center justify-center items-center p-3", { hidden: error == null })}>
                {error}
            </div>
            <div className={classNames(skeleton, { hidden: hasBeenLoaded || error != null })}></div>
        </div>
    )
}

export default GalleryThumbnail
