// Fluffle.UI/src/components/search-result-mobile.tsx
import * as React from 'react'
import { SearchResult, SearchResultItem } from '../services/api';
import GalleryThumbnail from './gallery-thumbnail';
import Icon from './icon';

const GalleryCard = ({ data }: { data: SearchResultItem }) => {
    return (
        <a className="square w-1/2 sm:w-1/3 md:w-1/4 p-1 block relative" href={data.location} target="_blank" rel="noreferrer">
            <div className="absolute left-0 top-0 w-full h-full p-inherit">
                <div className="relative w-full h-full rounded overflow-hidden">
                    <div className={`absolute top-0 left-0 w-7 p-0.5 bg-gradient-${data.match.class} rounded-tl rounded-br z-10`}>
                        <Icon name={data.platform} />
                    </div>
                    <div className="absolute bottom-0 w-full whitespace-nowrap overflow-hidden overflow-ellipsis p-1 bg-black bg-opacity-80 text-xs text-light-100 z-10">
                        By <span className="font-semibold">{data.credits.join(" & ")}</span>
                    </div>
                    <div className="absolute top-0 left-0 w-full h-full">
                        <GalleryThumbnail thumbnail={data.thumbnail} hasBlur={false} />
                    </div>
                </div>
            </div>
        </a>
    )
}

const SearchResultMobile = ({ data }: { data: SearchResult }) => {
    return (
        <div className="flex lg:hidden flex-col items-center space-y-6">
            <img className="rounded" src={data.parameters.imageUrl} style={{ maxWidth: "75vw", maxHeight: "50vh" }} />
            <div className="text-center">
                <div className="text-muted">
                    Searched {data.stats.count.toLocaleString()} images in {data.stats.elapsedMilliseconds.toLocaleString()} ms
                </div>
                <div className="text-3xl">
                    {
                        {
                            0: "Oh noes! Couldn't find what you're looking for",
                            1: "Jolly good! We found a similar image"
                        }[data.probableResults.length] || "Jolly good! We found similar images"
                    }
                </div>
            </div>
            <div className="flex flex-wrap justify-evenly w-full">
                {data.probableResults.concat(data.improbableResults).slice(0, 12).map(item => (
                    <GalleryCard key={item.id} data={item}></GalleryCard>
                ))}
            </div>
        </div>
    )
};

export default SearchResultMobile

// Fluffle.UI/src/app/search-result-mobile/search-result-mobile.component.ts
import { Component, OnInit } from '@angular/core';
import { SearchResultImage } from '../api.service';
import { PlatformHelperService } from '../platform-helper.service';
import { SearchResultGalleryComponent } from '../search-result-gallery.component';
import { SearchResultService } from '../search-result.service';

@Component({
  selector: 'app-search-result-mobile',
  templateUrl: './search-result-mobile.component.html',
  styleUrls: ['./search-result-mobile.component.scss']
})
export class SearchResultMobileComponent extends SearchResultGalleryComponent implements OnInit {
  images: SearchResultImage[];

  constructor(searchService: SearchResultService, public platformHelper: PlatformHelperService) {
    super(searchService);
    
    this.images = searchService.result.images.slice(0, 12);
  }

  ngOnInit(): void {
    super.ngOnInit();
  }
}

<div class="d-lg-none">
    <div class="d-flex flex-column mt-3 bg-dark rounded overflow-hidden position-relative shadow-sm">
        <div class="position-relative text-center">
            <img [src]="searchService.result.imageUrl" class="mobile-search-result-searched-image rounded mt-2">
        </div>
        <div class="mx-2 my-3">
            <div class="text-muted text-center">Searched {{ searchService.result.count.toLocaleString() }} images in {{
                searchService.result.elapsedMilliseconds }} ms</div>
            <h1 class="text-center" [ngSwitch]="searchService.excellentImages.length">
                <span *ngSwitchCase="0">Oh noes! Couldn't find what you're looking for</span>
                <span *ngSwitchCase="1">Jolly good! We found a similar image</span>
                <span *ngSwitchDefault>Jolly good! We found similar images</span>
            </h1>
        </div>
        <div>
            <div class="d-flex flex-wrap justify-content-between">
                <a class="mobile-item" *ngFor="let image of images" [href]="image.viewLocation" target="_blank">
                    <div class="mobile-search-result-gallery-image-holder">
                        <div class="position-relative h-100 w-100">
                            <img [src]="platformHelper.getLogo(image.platform)" class="mobile-item-site"
                                [ngClass]="platformHelper.getLabel(image)">
                            <div class="thumbnail-container">
                                <app-gallery-thumbnail [thumbnail]="image.thumbnail" [hasBlur]="false">
                                </app-gallery-thumbnail>
                            </div>
                            <div class="mobile-result-artist">
                                <b *ngIf="image.credits.length === 0">Unknown artist</b>
                                <span *ngIf="image.credits.length !== 0">By <b>{{ image.creditsString }}</b></span>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>
